spring:
  application:
    name: auth-service
  rabbitmq:
    host: rabbitmq # RabbitMQ 컨테이너 이름
    port: 5672
    username: user
    password: password
    listener:
      simple:
        auto-startup: true
        acknowledge-mode: auto
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
logging:
  level:
    root: INFO
    com.example.authservice: DEBUG
    com.example.authservice.service.AuthService: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    enabled: true
  instance:
    prefer-ip-address: true