logging:
  level:
    org.springframework.web: TRACE
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: TRACE
    com.example.apigateway.filter: TRACE
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: auth-service
          uri: http://auth-service:8080
          predicates:
            - Path=/api/auth/**
        - id: user-service
          uri: http://user-service:8080
          predicates:
            - Path=/api/users/**
        - id: subscription
          uri: http://subscription:9090
          predicates:
            - Path=/api/subscriptions/**
          filters:
            - PreserveHostHeader=true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer